### ISSUE TITLE
when entering name, duplicate characters appears

### ISSUE THREAD

**Issue by andy5995** [UltraStar-Deluxe/USDX#145]
On the single player -> sing menu, when I am prompted for Player 1's name:
I type "a", and "Aa" is output. The whole line will read "AaNnDdYy".

Backspace only registers one keypress, as it should.

In order to start troubleshooting this, I'll mention this thread:

[SDL 2.0.4 update broke hotkeys on windows (Opening team chat with key T automatically writes a t in input dialog)](http://trac.wildfiregames.com/ticket/3870)

Another project I know of - MegaGlest - had an issue where when someone pressed the key to toggle team chat, it would toggle to team chat and then immediately back to global chat, as if the hotkey had been pressed twice. There's no ticket for it that I know of, but it was discussed on IRC, and the maintainers came to the conclusion that it was directly related to libsdl-2.0.4

Oh, I'm on Debian Linux Jessie, amd64
[config.log.zip](https://github.com/UltraStar-Deluxe/USDX/files/512816/config.log.zip)

**Comment by basisbit** [comment]
looks like a sdl 2.0.4 bug to me. It sends the key-pressed event twice and with wrong Capitalization. SDL 2.0.5 should be released soon which might fix the issue for you. I so far haven't seen this issue on other OS with SDL 2.0.4

**Comment by RattleSN4K3** [comment]
In addition, the whole _key-pressend-event-to-text_ implemenation should be re-written using the (new) SDL2 events for text input.

**Comment by basisbit** [comment]
this game now supports SDL 2.0.5 and the only case where I was able to see a similar problem is fixed now. Please check if this also fixes the typing issue for you.

**Comment by philbox2** [comment]
i have the newest version of ultrastar and the problem still exists. I am running windows 10 64 bit.

**Comment by basisbit** [comment]
thats most likely because there was no release of usdx after the issue was fixed.
