### ISSUE TITLE
Black screen on Ubuntu 16.04 with Nvidia 364.19 drivers

### ISSUE THREAD

**Issue by skerit** [UltraStar-Deluxe/USDX#155]
UltrastarDX works on my Ubuntu 16.04 Macbook Pro with Intel drivers, but on my desktop I'm only getting a black screen.

The logfiles look the same, I see no new error messages popping up. I hear sound and all, the screen just remains black.

Any idea what could be the cause?

**Comment by basisbit** [comment]
check your OpenGL support. Also try if switching from fullscreen to windowed mode (F11 key or Alt+Enter) helps.

**Comment by basisbit** [comment]
also, in the logs, what OpenGL Vendor and OpenGL Renderer does it report?

**Comment by skerit** [comment]
I tried fullscreen and windowed mode, but no luck.

The log actually doesn't report any of those, unlike on the Macbook where it clearly says "Intel"...

```
STATUS: SDL_Init [UGraphic.Initialize3D]
STATUS: Use config resolution [SDL_SetVideoMode]
STATUS: Creating window [SDL_SetVideoMode]
STATUS: Set Video Mode...   Windowed [SDL_SetVideoMode]
INFO:   OpenGL vendor  [UGraphic.InitializeScreen]
INFO:   OpenGL renderer  [UGraphic.InitializeScreen]
INFO:   OpenGL version  [UGraphic.InitializeScreen]
INFO:   OpenGL vendor  [TTextureUnit.Create]
INFO:   OpenGL renderer  [TTextureUnit.Create]
INFO:   OpenGL version  [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: 0 [TTextureUnit.Create]
STATUS: TDisplay.Create [UGraphic.Initialize3D]
STATUS: Loading Font Textures [UGraphic.Initialize3D]
STATUS: Building Fonts [LoadTextures]
```

**Comment by basisbit** [comment]
In that case, your issue is caused by either a bug in SDL2 on your system or broken OpenGL  1.3 support. You could try Mesa OpenGL software-rendering to figure out if the issue is actually caused by your graphics card drivers or not.

**Comment by skerit** [comment]
I tried starting it with the `LIBGL_ALWAYS_SOFTWARE=1` env variable set, but that didn't do much. I read that that doesn't seem to work anymore with the nvidia drivers, anyway.

Is there some other way to start it with software rendering?

**Comment by basisbit** [comment]
you might be able to get some help in the ubuntu forums. Sorry, but this issue seems to not specifically be related to USDX :-\

**Comment by kattelus** [comment]
@skerit any luck making nvidia drivers and USDX working together? I had exactly same problem.

**Comment by basisbit** [comment]
we only use SDL2 for getting the OpenGL context. So there is not much we currently can do. Could you please check if any older version of usdx runs correctly? Maybe the usdx 1.1 release?

**Comment by sebastian-garn** [comment]
Hey kattelus,
the last two days I was struggling around with the exact same problem skerit was mentioning. I found out that ultrastardx was starting fine as long I have used the nouveau driver. But since the hardware acceleration support did not work properly with nouveau on my machine it was no option for me. I finally found a way to make it work with the nvidia proprietary drivers: I manually downloaded the drivers and installed them instead of using the driver utility of Linux Mint.

Next step for me (but that is not related to the problem) is to somehow tell USDX to make use of HW acceleration since I am running USDX on a less powerful machine. top shows around 190% of cpu load when playing vids without HW acceleration. Playing same vid in vlc (wich I configured to make use of HW acceleration) reduced it to 30% cpu load.

**Comment by basisbit** [comment]
sound like ffmpeg is not choosing the best / fastest codec for your system. Is that something arm cpu based?

**Comment by kattelus** [comment]
I have laptop with two graphic cards. Integrated Intel (power saving) and more powerful Nvidia (performance mode). It seems that if I switch to Intel everything is working fine but if using Nvidia it just leaves window blank.

It also seems that somehow log in Intel case shows correct information e.g.
INFO:   OpenGL vendor Intel Open Source Technology Center [UGraphic.InitializeScreen]
INFO:   OpenGL renderer Mesa DRI Intel(R) Sandybridge Mobile  [UGraphic.InitializeScreen]
INFO:   OpenGL version 3.0 Mesa 12.0.6 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor Intel Open Source Technology Center [TTextureUnit.Create]
INFO:   OpenGL renderer Mesa DRI Intel(R) Sandybridge Mobile  [TTextureUnit.Create]
INFO:   OpenGL version 3.0 Mesa 12.0.6 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]

But in case of Nvidia:
INFO:   OpenGL renderer  [UGraphic.InitializeScreen]
INFO:   OpenGL version  [UGraphic.InitializeScreen]
INFO:   OpenGL vendor  [TTextureUnit.Create]
INFO:   OpenGL renderer  [TTextureUnit.Create]
INFO:   OpenGL version  [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: 0 [TTextureUnit.Create]

**Comment by sebastian-garn** [comment]
@basisbit
No, its not.

This is the configuration:
Intel Atom 330, 2x 1.60GHz
4 GB of RAM
NVIDIA GeForce 9400M

Let's not talk about that problem within this issue. I will probably create a new one in case I am not able to get rid of it.

@katelus Just in case you need some kind of comparison:

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: ION/integrated/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.102
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3.0 NVIDIA 340.102
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.102 340.102
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
OpenGL ES profile extensions:

By comparing this output to the previous output (which I saved when it was NOT working) is that it is now version 340.102. Before, the driver utility of mint took version 340.101. I doubt that the problem was solved just by the newer version.

log shows:

INFO:   OpenGL vendor NVIDIA Corporation [UGraphic.InitializeScreen]
INFO:   OpenGL renderer ION/integrated/SSE2 [UGraphic.InitializeScreen]
INFO:   OpenGL version 3.3.0 NVIDIA 340.102 [UGraphic.InitializeScreen]
INFO:   OpenGL vendor NVIDIA Corporation [TTextureUnit.Create]
INFO:   OpenGL renderer ION/integrated/SSE2 [TTextureUnit.Create]
INFO:   OpenGL version 3.3.0 NVIDIA 340.102 [TTextureUnit.Create]
INFO:   OpenGL TextureNPOT-support: -1 [TTextureUnit.Create]

Before, all the information were missing (like in your log output). So again I would recommend manually reinstalling nvidia driver or testing out nouveau.

**Comment by hoehermann** [comment]
I experienced this problem and overcame it, too.
I enabled the linker's debug output via environment variable

    env LD_DEBUG=files ultrastardx

It produced a tremendous amount of error messages like this one:

    /usr/lib/x86_64-linux-gnu/libGL.so: error: symbol lookup error: undefined symbol: glXGetCurreentDisplay (fatal)

I then discovered that the loaded `/usr/lib/x86_64-linux-gnu/libGL.so` was actually a link to the mesa implementation and not the nivdia implementation (I suppose this is bound to happen if you have one of those laptops with hybrid graphics).

    $ ls -l /usr/lib/x86_64-linux-gnu/libGL.so
    `/usr/lib/x86_64-linux-gnu/libGL.so -> mesa/libGL.so`

I then used

    find /usr/lib -name 'libGL.so'

to find nvidia's `libGL.so` residing in `/usr/lib/nvidia-375` (or `/usr/lib/nvidia-340` on my older machine). I can now properly start UltraStar Deluxe with a preferred path to load system libraries from:

    env LD_LIBRARY_PATH=/usr/lib/nvidia-375 ultrastardx

Strange enough: Other OpenGL applications, including SDL2 ones, are working just fine without this tweak.

**Comment by hoehermann** [comment]
@basisbit, I recommend to leave the issue closed. My solution works in an environment with a weird OpenGL subsystem. Your original statement "this issue seems to not specifically be related to USDX" is still valid. It should not be USDX's task to determine which of the available libGL.so versions to use.

**Comment by basisbit** [comment]
I opened this issue so I don't forget to check where the libgl.so is referenced. Maybe this is a quick and easy fix...

**Comment by silelmot** [comment]
Had just the same issues with Ubuntu and Nvidia 851. env-settings didnt worked out. i ended up deleting the /usr/lib/x86_64-linux-gnu/libGL.so and now it works like a charm...

**Comment by xwarman** [comment]
Hi. 
First I just started USDX without Nvidia Graphics, just with intel graphic card. USDX worked so far. afterwards Id try to start usdx on the same system with same config but with nvidia card installed. (propertery drivers installed in both cases) Now USDX had just a black screen, no matter what parameters Id used. 
Then I just renamed the /usr/lib/x86_64-linux-gnu/libGL.so and it worked! 
What does that file do? Is it important? 
USDX worked before well on Ubuntu 12.04 ++, same System, Version 1.1;
It does not work since Ubuntu 16.04 Upgrade until today. I think the libGL.so was the main problem. 
A friend of mine has also an nvidia configurated ubuntu 16.04 System with the same problem. 
So, do I need the libGL.so file? May you fix that problem? 
Thanks for your great work so far.

**Comment by s09bQ5** [comment]
See pull request #317.

**Comment by hoehermann** [comment]
@silelmot @xwarman 
*libGL.so - What does that file do? Is it important?*
It is important. It is very important. libGL.so is the dynamic library wich offers all the OpenGL functions. Without this library, you cannot use OpenGL on your system. So please never delete this file, regardless where you find it.  
Now why does this important benevolent file cause problems?  
By default on linux, the OpenGL functions are implemented by the mesa project. The proprietary nvidia drivers come with their own implementation of the very same OpenGL functions, specially optimized towards nvidia hardware.
Now some applications (or subsystems, in the case of USDX) explicitly demand a specific implementation. That is why you do not want to delete the libGL.so provided by mesa. Other applications rely on the system being properly configured globally and just ask for any libGL.so. These applications usually load the first libGL.so they find.  
So you end up with different implementations of OpenGL provided by different files named libGL.so, residing in different directories. By explicitly defining `LD_LIBRARY_PATH`, the dynamic library loader knows where to look first.

I hope this information proves helpful to you.

**Comment by barbeque-squared** [comment]
Is this issue still relevant? Or can it be closed?

**Comment by s09bQ5** [comment]
I believe this has been fixed 5 years ago with a435133e4894722949efd54e59870252fdb8f410.

**Comment by barbeque-squared** [comment]
Yeah that looks like it should do it. Maybe it's still broken on this particular OS/driver combination, but that can just go into a new issue then.

(I'm going through all of the open issues and seeing what they're about)
