### ISSUE TITLE
Doubled keyboard letters

### ISSUE THREAD

**Issue by axeway** [UltraStar-Deluxe/USDX#271]
### Actual behaviour

Exactly this in the song list while looking for ''somesong'', hot key ''j''
actual text: "jSsOoMmEeSsOoNnGg''. This only in this game, no problems with ''world edition'' for example

### Expected behaviour

text:  "somesong"

### Steps to reproduce

Windows 10 64bit, AMD APU, any text introduced while ingame exclusively.
For example

1. Open the ultrastardx.exe
2. Click on Songs, button J
3. Write

### Details

Provide some additional information:

- USDX version: latest
- Operating System + version: 15068

**Comment by basisbit** [comment]
this issue was already fixed by c2f3833 in february by @daniel-j ( #240 )

**Comment by basisbit** [comment]
please wait for the upcoming release of USDX for this fix to be included.

**Comment by h3llyka** [comment]
I see this (and another similar thread) has been considered resolved and closed. I just downloaded the last version and it is still an issue. Any recommendations?

**Comment by Avispa** [comment]
Still plans to update the release? Almost 2 years later and it's still 1.3.5 beta and still has the same bug. Impossible to search for songs this way.

**Comment by s09bQ5** [comment]
@Avispa, you must have missed the 2017.8.0 release.
