### ISSUE TITLE
USDX randomly throws errors sometimes (seldom)

### ISSUE THREAD

**Issue by natrius** [UltraStar-Deluxe/USDX#542]
### Actual behaviour

Tell us what happens

![grafik](https://user-images.githubusercontent.com/7243447/91044432-8d724780-e615-11ea-9e37-19dd52503800.png)

```

---------------------------
UltraStar Deluxe - www.usdx.eu V 2020.4.0 stable Build
---------------------------
Sorry, an error ocurred! Please report this error to the game-developers. Also check the Error.log file in the game folder.

Stacktrace:
Exception class: ERangeError
Message: Range check error

  $00471CCD  TINI__SAVEWEBCAMSETTINGS,  line 2154 of base/UIni.pas
  $0051B49A  TSCREENOPTIONSWEBCAM__PARSEINPUT,  line 106 of screens/UScreenOptionsWebcam.pas
  $0043692C  TDISPLAY__PARSEINPUT,  line 674 of menu/UDisplay.pas
  $0044F4BB  CHECKEVENTS,  line 565 of base/UMain.pas
  $0044E757  MAINLOOP,  line 322 of base/UMain.pas
  $0044E59C  MAIN,  line 266 of base/UMain.pas
  $00402B72  main,  line 411 of ultrastardx.dpr
---------------------------
OK   
---------------------------

```

### Expected behaviour

No error.

### Steps to reproduce

Not reproduceable right now, but a smilar error happened before already. 

### Details

Provide some additional information:

- USDX version: 2020.4.0
- Operating System + version: Windows 7

**Comment by HermannDppes** [comment]
Looking into UIni.pas I find starting at line 211:
```
      // WebCam                                                                  
      WebCamID:         integer;                                                 
      WebcamResolution: integer;                                                 
      WebCamFPS:        integer;                                                 
      WebCamFlip:       integer;                                                 
      WebCamBrightness: integer;                                                 
      WebCamSaturation: integer;                                                 
      WebCamHue:        integer;                                                 
      WebCamEffect:     integer;
```
But starting at line 2149:
```
    // WebCam                                                                    
    IniFile.WriteInteger('Webcam', 'ID', WebCamID);                              
    IniFile.WriteString('Webcam', 'Resolution', IWebcamResolution[WebcamResolution]);
    IniFile.WriteInteger('Webcam', 'FPS', StrToInt(IWebcamFPS[WebCamFPS]));      
                                                                                 
    IniFile.WriteString('Webcam', 'Flip', IWebcamFlip[WebcamFlip]);              
    IniFile.WriteString('Webcam', 'Brightness', IWebcamBrightness[WebcamBrightness]);
    IniFile.WriteString('Webcam', 'Saturation', IWebcamSaturation[WebcamSaturation]);
    IniFile.WriteString('Webcam', 'Hue', IWebcamHue[WebcamHue]);                 
    IniFile.WriteInteger('Webcam', 'Effect', WebcamEffect); 
```

So, the `WebcamFlip` in line 2154 is the first where the casing does not match. Could this be the source of the error? I do not know enough about Pascal. I mean it *should* be case-insenstive, right? But it is a strange coincidence.

**Comment by HermannDppes** [comment]
It is indeed coincidence, the error is clearly the following line:
```
  WebCamFlip := ReadArrayIndex(IWebcamFlipTranslated, IniFile, 'Webcam', 'Flip', IGNORE_INDEX, 'On');
```
where it should read `IWebcamFlip` instead (without the `Translated`). I'll prepare a PR.

**Comment by natrius** [comment]
Interesting, because it happened just once. The next time it did not happen again, will check again after another restart. Thanks for looking into it @HermannDppes  :)

**Comment by HermannDppes** [comment]
Do you recall whether you changed around themes (or at least opened the corresponding submenu) in the USDX session that threw this error?

**Comment by HermannDppes** [comment]
I have a repro on a fresh build from the current master.
* Open USDX
* Go to Settings/Game and change the language to Deutsch (German)
* Go to Optionen/Design (Settings/Themes in Englisch) and change the Design from Modern to Deluxe
* Go to Optionen/Webcam (Settings/Webcam in English) and leave again

This will consistently crash. The crash does not occur otherwise as changing a theme is one of the rare instances (maybe the only one?) where the Ini file is read after the initial read, during which the locale is still identical with the English version.

**Comment by natrius** [comment]
Yes, pretty sure i changed the theme. Was looking at the themes and so on.

**Comment by dgruss** [comment]
could be related to #1178

**Comment by dgruss** [comment]
i am pretty sure this is fixed in #1178

**Comment by barbeque-squared** [comment]
The ITranslated line is still there (it's 1730 these days) and I don't really see how 1178 relates to this:
https://github.com/UltraStar-Deluxe/USDX/blob/b2cc96db13c34be71edefdf24da8de442726191b/src/base/UIni.pas#L1730

The commented repro is rather clear, it either still crashes or it doesn't. Don't post non-committal comments, instead comment what the behaviour actually is now that 1178 is merged (or if it's still the same, don't comment at all).

What _is_ relevant is that since #1081 all platforms will throw ERangeError; before that this would have only shown on Windows computers.

**Comment by dgruss** [comment]
I am not sure that this is really the read? The crash (first post in this issue) report says:
  $00471CCD  TINI__SAVEWEBCAMSETTINGS,  line 2154 of base/UIni.pas

And *that* should be fixed.

Sure it says RangeCheckError - but I don't know what checks happen internally in these functions.

**Comment by barbeque-squared** [comment]
Ah I see, I missed that 1178 simply swallows _any_ Exception, not just the I/O-related ones. We should still let things like divide-by-zero or this ERangeError crash the program, because they're different issues that aren't related to whether a file is readable/writable or not.

_Probably_ it should only catch [EInOutError](https://www.freepascal.org/docs-html/rtl/sysutils/einouterror.html), I'll have something later today.

**Comment by barbeque-squared** [comment]
Yeah so I just tried the repro commented in 2020, it still crashes just fine. Bottom line: if people could just take the literally 2 minutes next time before commenting things like "i am pretty sure this is fixed in..." and actually try these things, that would save me a great deal of time and this issue about a dozen unrelated comments, thanks.

**Comment by dgruss** [comment]
you're right, my mistake, i just looked at the initial crash

fixed it in #1275
