### ISSUE TITLE
Updater broken

### ISSUE THREAD

**Issue by s09bQ5** [UltraStar-Deluxe/USDX#771]
### Actual behaviour

The updater fetches the current version from Github and displays it correctly but then substitutes wrong numbers in the URL to download the installer. It then repeatedly tries to download the installer using HTTP while ignoring the 301 redirect to HTTPS. Eventually it runs into a timeout and says that the update failed.

### Expected behaviour

The updater should download the installer from the correct URL and it should follow 301 redirects.

### Steps to reproduce

1. Install 2023.9.0
2. Run the updater

### Details

Provide some additional information:

- USDX version: 2023.9.0
- Operating System + version: Windows 10

**Comment by dgruss** [comment]
should be fixed in #1170

**Comment by barbeque-squared** [comment]
I don't really know how to start the updater, but I think this should indeed be fixed with the next release? I'Il link it to 1170 for now, if for some reason it isn't fixed once the next release (or the one after _that_ I guess?) is out, then either reopen this or just make a new one.
